#baseURL = 'https://www.covenant.srl/'
baseURL = '/'

languageCode = 'en-us'
title = 'Covenant Srls'

theme = "covenant-theme"
publishDir = "docs"
staticDir = ['assets']

defaultContentLang = 'it'

[params]
  copyright = "Copyright Â© 2022 Covenant Srls. P.IVA 14635081004. Via Flavia, 47 - 00187 Roma. Tutti i diritti riservati."
  description = "The New Web3 Software and Privacy Company"
